### ISSUE TITLE
特征值 的计算是否有问题？

### ISSUE THREAD

**Issue by schumipush** [Amoiensis/Matrix_hub#5]
您好

非常感谢开源代码

关于特征值的计算结果，我做了一个简单的测试，对比【原矩阵 x 特征向量矩阵】与【特征向量矩阵 x 特征值矩阵】，发现这两个矩阵的最后一行不一致（前面几行都是一致的）。是否说明特征值的计算结果有问题？

![image](https://user-images.githubusercontent.com/22997461/171214072-0cd96a5b-252e-4df3-a69e-a8447a94a9a4.png)

输出结果如下：

![image](https://user-images.githubusercontent.com/22997461/171214480-0f999cc1-e10c-4213-8739-86f5360fa336.png)

**Comment by 645770225** [comment]
他的特征值计算确实有问题，我检查发现是QR分解时有误，转上Hessenberg矩阵也犯了同样的错误，我新发一个issue指出吧

**Comment by Amoiensis** [comment]
@schumipush @645770225 
你好，感谢对本项目的关注和使用！
关于这个问题，解决方案请参考 645770225 开的新issue [M_householder 函数修正- issue8](https://github.com/Amoiensis/Matrix_hub/issues/8)。

**Comment by Amoiensis** [comment]
> 您好
> 
> 非常感谢开源代码
> 
> 关于特征值的计算结果，我做了一个简单的测试，对比【原矩阵 x 特征向量矩阵】与【特征向量矩阵 x 特征值矩阵】，发现这两个矩阵的最后一行不一致（前面几行都是一致的）。是否说明特征值的计算结果有问题？
> 
> ![image](https://user-images.githubusercontent.com/22997461/171214072-0cd96a5b-252e-4df3-a69e-a8447a94a9a4.png)
> 
> 输出结果如下：
> 
> ![image](https://user-images.githubusercontent.com/22997461/171214480-0f999cc1-e10c-4213-8739-86f5360fa336.png)


您好，这个问题在新版本 Matrix_Hub_v1.52 中已经解决，欢迎更新和使用新版本，此外新版本还新增插件部分，可以尝试求解线性规划问题。
