### ISSUE TITLE
matrix.h的问题

### ISSUE THREAD

**Issue by Mctianxiu** [Amoiensis/Matrix_hub#6]
你好   请问 
dev  显示 matrix.h: No such file or directory.  怎么解决

**Comment by Amoiensis** [comment]
您好，如果您使用的是Dev C++，需要：
1. 需要构建新项目（命令行项目）;
2. 将您的源文件 (e.g. demo.c)，与本项目的 matrix.h / state.h / (帮助文档，如需要) 添加到项目中；
3. 再进行编译运行；
如有任何其他问题欢迎和我联系（可以直接邮件: Amoiensis@outlook.com），再次感谢您对本项目的关注和支持。

**Comment by Mctianxiu** [comment]
谢谢 大佬的帮助！
