### ISSUE TITLE
请增加SVD分解的功能

### ISSUE THREAD

**Issue by yushuizha** [Amoiensis/Matrix_hub#7]
svd是矩阵分解中的常用函数，请增加svd的支持，谢谢

**Comment by Amoiensis** [comment]
您好
&nbsp; &nbsp; &nbsp;好的，收到，没问题，最近去支持一波。
祝 工作顺利
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Xiping.Yu




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Amoiensis/Matrix_hub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午2:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Amoiensis/Matrix_hub] 请增加SVD分解的功能 (Issue #7)





 
svd是矩阵分解中的常用函数，请增加svd的支持，谢谢

**Comment by Amoiensis** [comment]
> svd是矩阵分解中的常用函数，请增加svd的支持，谢谢

您好，在 Matrix_Hub_v1.52版本中添加了矩阵SVD分解功能，详见函数 M_SVD，欢迎更新尝试新版本。
