### ISSUE TITLE
QR分解求得的Q矩阵不是正交矩阵

### ISSUE THREAD

**Issue by wtyhainan** [Amoiensis/Matrix_hub#9]
将代码中的第1688行
D->data[i] = (Ri->data[i*dim+i]<0)?-1:1;
改为
*(D->data + i*dim + i) = (Ri->data[i*dim+i]<0)?-1:1;

**Comment by Amoiensis** [comment]
您好：

感谢您对本项目的关注和使用，这个问题已经在 最新发布的Matrix_Hub_v1.52 版本中得到修复，欢迎您去更新使用。

对于这个问题的修改已经在代码中添加对您的感谢与该ISSUE的修改来源。

此外，新发布的版本还添加了插件部分，如果您在您的使用中有有趣的、实用的插件的，欢迎您与我们分享，也非常欢迎贡献代码，谢谢。
